### ISSUE TITLE
Input latency introduced

### ISSUE THREAD

**Issue by thetooth** [db47h/gio#2]
In last commit 66b140f there is now a delay when typing into editor fields or clicking buttons. It seems to vary anywhere between a few hundred ms and 1 second.

Reproduce by building kitchen example and holding down a key in either editor.

**Comment by db47h** [comment]
Sorry about the late response, I'm in the process of rewriting the event loop with vsync enabled instead of a timer.

I did however test and did not notice any lag and I have a fairly slow CPU. What's your configuration (CPU and OS ?). 

While it may not seem relevant, could you test with 8e2f737dca08f01e536ccb62d80a3184ab968723 and 8294521d012f7c1693624bea6987f40b0a9592e8 ?

**Comment by db47h** [comment]
Could you also test with the latest commit which uses a vsync based event loop?

**Comment by thetooth** [comment]
With 8e2f737 and 8294521 no issue.
Latest commit has broken rendering, no label widgets are rendered or take up correct amount of space so layout is also messed up. And there does not seem to be any events being propagated i.e. closing the window does not work.

My test system is manjaro 18.1.1, CPU: i7-4770, GPU: Intel mesa DRI. It's not going to be a resource issue, I think the issue is related to Ppoll to Poll change, perhaps it is not returning immediately, it does seem to wake up if you generate a lot of window events.

**Comment by db47h** [comment]
6df329c has no change in the event loop, so it's expected to behave as 66b140f.

I wasn't expecting a resource issue but rather a different behavior on a much faster machine. What do you mean by "has no events"?

Also you might be right about poll vs. ppoll, I did notice a slight change in CPU usage when switching but did not investigate further. In 0524e176e112e7f77061e7b9239560089e823de6 I did swicth back to using ppoll(). Let's hope that this fixes it. If it doesn't, I can just skip the call (which is useless if we don't want it to wait), but that will need a bit more work.

**Comment by db47h** [comment]
Well, here's 1db538f41caa763ff11b0f47d88e18abfe803fe2 where the p?poll call is skipped entirely when not needed.

**Comment by thetooth** [comment]
Yeah this fixes it, thank you!

**Comment by db47h** [comment]
Thank you for your feedback!
